# Permalinks
permalink:           pretty

# Setup
title:               proxpero
url:                 http://proxpero.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name: Todd Olsen
  twitter: https://twitter.com/proxpero
  github: https://github.com/proxpero
  email: proxpero@gmail.com

# This is the list of pages to include in the header of the website.
pages_list:
  Projects: '/projects/'
  Archive: '/archive/'
  About: '/about/'

analytics_id: UA-66868018-1

# Gems
gems:
  - jekyll-paginate
