# Permalinks
permalink:           pretty

# Setup
title:               proxpero
# tagline:             such as it is.
url:                 http://proxpero.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Todd Olsen
  url:               https://twitter.com/proxpero
  email:             proxpero@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/proxpero


# This is the list of pages to include in the header of the website.
pages_list:
  Projects: '/projects/'
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-paginate
